</div> <!-- /container -->
<footer>
	<ul>
		<li><img src="images/logos_footer/mart.jpg"/></li>
		<li><img src="images/logos_footer/martimx.jpg"/></li>
		<li><img src="images/logos_footer/sc.jpg"/></li>
		<li><img src="images/logos_footer/cc.jpg"/></li>
		<li><img src="images/logos_footer/ed.jpg"/></li>
		<li><img src="images/logos_footer/sf.jpg"/></li>
	</ul>
</footer>
</div><!-- wrapper -->