<!DOCTYPE html>
<html>
  <head>    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Comunicaci&oacuten interna</title>
    <link href="css/bootstrap.min.css" rel="stylesheet">    
    <link href="css/main.css" rel="stylesheet">
  </head>
  <body>
    <div id="wrapper">
      <div class="image_izquierda"></div>
      <div class="image_derecha"></div> 
